version: 2
jobs:
  build:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command: |
            apk add --no-cache py-pip
            pip install docker-compose==1.21.2
      - run:
          name: Build golang binary
          command: |
            apk add --no-cache go musl-dev
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
              -a -ldflags '-extldflags "-static"' app.go
      - run:
          name: Run tests
          command: |
            docker-compose up -d --build
            docker-compose exec -T test /run_test.sh
            docker-compose down
